
// Supabase configuration
export const SUPABASE_CONFIG = {
  url: "https://bqziykyifhqtzkjqbqph.supabase.co",
  anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxeml5a3lpZmhxdHpranFicXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzc1MjksImV4cCI6MjA1OTkxMzUyOX0.RKnAd0bEdTrQCGjdWgKv2MvgNvnxxypxgwbC2gbQTbY",
  serviceKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxeml5a3lpZmhxdHpranFicXBoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDMzNzUyOSwiZXhwIjoyMDU5OTEzNTI5fQ.npWjjLXqF58j790wVTpTj22mZPQENO9tle_vhiIVnU4"
} as const;

