
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqziykyifhqtzkjqbqph.supabase.co";
// Replace this placeholder with your actual service key
const SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxeml5a3lpZmhxdHpranFicXBoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDMzNzUyOSwiZXhwIjoyMDU5OTEzNTI5fQ.npWjjLXqF58j790wVTpTj22mZPQENO9tle_vhiIVnU4";

// Import the admin supabase client like this:
// import { adminSupabase } from "@/integrations/supabase/adminClient";

export const adminSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_KEY);